format: :JSON
skip_ssl_verification: false
host: localhost
port: 5000
send_warnings: false
commands:
  - cf
output_channels:
  - :STDOUT
thresholds:
  cpu:
    warning: 10
    critical: 1
  memory:
    warning: 100
    critical: 500
  disk:
    warning: 100
    critical: 500
