format: :JSON
skip_ssl_verification: false
commands:
  - cf
output_channels:
  - :STDOUT
thresholds:
  cpu:
    min: 10
    max: 1
  memory:
    min: 200
    max: 500
  disk:
    min: 100
    max: 500
